// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpcxpwfbjsuymecrpfpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwY3hwd2ZianN1eW1lY3JwZnB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0Mzk2NzIsImV4cCI6MjA2MDAxNTY3Mn0._TGPqKWiX1EYBUAVx1M1zR6Pl274_VqpxkwkaIOqkgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);